""" Config for the flocking simulation """
MAXIMUM_STEPS = 10
GRID_WIDTH = 20
GRID_HEIGHT = 20
VIEW_SCALING = 20
GRID_TOROIDAL = False
SEED = 4


AMOUNT_BIRDS = 30
AMOUNT_PREDATOR = 1

SAFE_DISTANCE = 32
ISOLATION_DISTANCE = 32
MAXIMUM_COHESION_DISTANCE = 40


# TODO