""" Config for the flocking simulation """
MAXIMUM_STEPS = 10
GRID_WIDTH = 512
GRID_HEIGHT = 512
VIEW_SCALING = 5
GRID_TOROIDAL = True
SEED = 3


AMOUNT_BIRDS = 100
INITIAL_FLOCK_DISPERSION = 50
AMOUNT_PREDATOR = 1
MAX_VELOCITY_BIRD = 2
FUTURE_POSITION_VAR = 14  # w

SAFE_DISTANCE = 32
ISOLATION_DISTANCE = 32
MAXIMUM_COHESION_DISTANCE = 40


# TODO