""" Config for the flocking simulation """
MAXIMUM_STEPS = 10
GRID_WIDTH = 50
GRID_HEIGHT = 50
VIEW_SCALING = 10
GRID_TOROIDAL = False
SEED = 0


AMOUNT_BIRDS = 100
AMOUNT_PREDATOR = 1

SAFE_DISTANCE = 32
ISOLATION_DISTANCE = 32
MAXIMUM_COHESION_DISTANCE = 40


# TODO